### ISSUE TITLE
Map objects disappearing

### ISSUE THREAD

**Issue by Necroso** [DizzasTeR/VCMP-Lua#18]
Objects created with Object:new disappear from the map after a few minutes.

Script:
```lua
initTime = 0
Event.bind("onServerInit", function()
    loadObject(os.time())
	Timer.create(function()
		if Object.count() < 1 then
			Logger.info("No objects found | time: " .. os.time())
			Logger.info("After: " .. os.time() - initTime .. " secs")
		end
	end, 50, -1)
end)

function loadObject(timestamp)
	initTime = timestamp
	Object:new(4499, 1, -305.76, -481.706, 20.7062, 255)
	Logger.info("Object count: " .. Object.count() .. " | time: " .. timestamp)
end
```

Log:
![](https://imgur.com/SnlX0Nr.png)

**Comment by rasikhq** [comment]
Will look into it

**Comment by rasikhq** [comment]
@Necroso Can you also perform this test with any other elements as well, maybe with object also add a vehicle, a pickup maybe and see if they also disappear

**Comment by Necroso** [comment]
> @Necroso Can you also perform this test with any other elements as well, maybe with object also add a vehicle, a pickup maybe and see if they also disappear

@DizzasTeR Yes, same problem with Vehicles, Pickups and Checkpoints.

**Comment by rasikhq** [comment]
@Necroso Okay I believe the reason it is happening is because of [Garbage Collection](https://en.wikipedia.org/wiki/Garbage_collection_(computer_science)). So to avoid it, you must store the reference to the instanced elements somewhere so that they don't get garbage collected when it runs and finds out nothing is holding onto these elements.

**Comment by Necroso** [comment]
Well, that solved the problem. Nothing disappears anymore. 😄

Thanks. @DizzasTeR
